# file: .travis.yml
language: objective-c

before_install:
- brew update
- brew outdated xctool || brew upgrade xctool
- gem install xcpretty -N


script:

# - xctool -project Swift2MIDI.xcodeproj -scheme "Swift2MIDI" -sdk iphoneos -configuration Debug -PBXBuildsContinueAfterErrors=0 test | xcpretty -c

#- xctool -project Swift2MIDI.xcodeproj -scheme "Swift2MIDI" -sdk iphoneos9.0 -configuration Debug -destination "platform=OS X" -PBXBuildsContinueAfterErrors=0 test | xcpretty -c

- xctool clean build -project Swift2MIDI.xcodeproj -scheme Swift2MIDI  | xcpretty -c
- xctool test -project Swift2MIDI.xcodeproj -scheme Swift2MIDITests  | xcpretty -c


# http://docs.travis-ci.com/user/languages/objective-c/


